version: '3.8'

services:
  database-mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bantolap@123
      MYSQL_DATABASE: test1
    ports:
      - "3307:3306"
    expose:
      - 3306
  
  backend:
    build:
     context: ../../server
     dockerfile: Dockerfile
    restart: unless-stopped
    environment:
    #  DB_HOST: host.docker.internal
      - DB_PORT=3306
      - DB_HOST=database-mysql
    ports:
      - 8080:8080
