version: '3.8'

services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bantolap@123
      MYSQL_DATABASE: test1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
  
  backend:
    build:
     context: ../server
     dockerfile: Dockerfile
    restart: unless-stopped
    environment:
    #  DB_HOST: host.docker.internal
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - URL_REACT=http://localhost
    ports:
      - 8080:8080
    expose:
      - 8080
  
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_data: